
Description: >
    This template will provision the  CodePipeline for the App.
    (Pipeline) GitHub -> TeamCity

Parameters:
   
    GitHubOwner:
        Description: Repository Owner
        Type: String
    
    GitHubRepo:
        Description: Repository Name
        Type: String
   
    GitHubBranch:
        Description: Repository Branch
        Type: String
   
    GitHubOAuthToken:
        Description: Access Token Generated via GitHub (https://github.com/settings/tokens)
        Type: String
   
    TeamCityServerUrl:
        Description: Url for TeamCity. Expected URL format, http[s]://host[:port]
        Type: String
   
    TeamCityBuildId:
        Description: Build Id for TeamCity Project
        Type: String
   
    TeamCityActionId:
        Description: Action Id for Codepipeline integration with TeamCity
        Type: String

Resources:
   
    CodePipelineServiceRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub 'cpsr-${AWS::StackName}'
            Path: /
            AssumeRolePolicyDocument: 
                Statement:
                    -
                        Effect: Allow
                        Principal:
                            Service:
                                - codepipeline.amazonaws.com
                        Action:
                            - sts:AssumeRole
            Policies:
                - 
                    PolicyName: !Sub 'cpsrp-${AWS::StackName}'
                    PolicyDocument:
                        Statement:
                            - Resource:
                                - !Sub 'arn:aws:s3:::${ArtifactBucket}/*'
                              Effect: Allow
                              Action: 
                                - s3:PutObject
                                - s3:GetObject
    
    ArtifactBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain

    TeamCityBuildActionType:
        Type: AWS::CodePipeline::CustomActionType
        Properties:
            Version: 1
            Category: Build
            Provider: TeamCity
            Settings:
                EntityUrlTemplate: '{Config:TeamCityServerURL}/viewType.html?buildTypeId={Config:BuildConfigurationID}'
                ExecutionUrlTemplate: '{Config:TeamCityServerURL}/viewLog.html?buildId={ExternalExecutionId}&tab=buildResultsDiv'
            ConfigurationProperties:
                - Name: TeamCityServerURL
                  Description: The expected URL format is http:[s]://host[:port]
                  Required: true
                  Key: true
                  Secret: false
                  Queryable: false
                  Type: String
                - Name: BuildConfigurationID
                  Description: TeamCity configuration external Id
                  Required: true
                  Key: true
                  Secret: false
                  Queryable: false
                  Type: String
                - Name: ActionID
                  Description: > 
                      Must be unique, match the corresponding field in TeamCity build trigger settings and satisfy regular expression pattern: [a-zA-Z0-9_-]+] and have length <= 20
                  Required: true
                  Key: true
                  Secret: false
                  Queryable: true
                  Type: String
            InputArtifactDetails:
                MaximumCount: 5
                MinimumCount: 0
            OutputArtifactDetails:
                MaximumCount: 5
                MinimumCount: 0

    Pipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties:
            RoleArn: !GetAtt CodePipelineServiceRole.Arn
            ArtifactStore:
                Type: S3
                Location: !Ref ArtifactBucket
            Stages:
                - Name: Source
                  Actions:
                      - Name: GitHubSource
                        ActionTypeId: 
                            Category: Source
                            Owner: ThirdParty
                            Version: 1
                            Provider: GitHub
                        Configuration:
                            Owner: !Ref GitHubOwner
                            Repo: !Ref GitHubRepo
                            Branch: !Ref GitHubBranch
                            OAuthToken: !Ref GitHubOAuthToken
                        OutputArtifacts:
                            - Name: AppRepo
                - Name: Build
                  Actions:
                      - Name: TeamCityBuild
                        ActionTypeId:
                            Category: Build
                            Owner: Custom
                            Version: 1
                            Provider: TeamCity
                        Configuration:
                            TeamCityServerURL: !Ref TeamCityServerUrl
                            BuildConfigurationID: !Ref TeamCityBuildId
                            ActionID: !Ref TeamCityActionId
                        InputArtifacts:
                            - Name: AppRepo
                        OutputArtifacts:
                            - Name: BuildOutput
